server:
  port: 8888
spring:
  application:
    name: houising-utilities-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maksimk99/housing-utilities-configs
          clone-on-start: true
  security:
    user:
      name: user
      password: root
